apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  nginx.conf: |
    events {
        worker_connections  1024;
    }
    http {
      upstream web {
        server web-svc.default.svc.cluster.local:5566;
      }
      server {
        location /web {
          proxy_pass http://web;
        }
      }
    }

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-3
  namespace: default
  labels:
    app: nginx
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx
    ports:
      - containerPort: 80
        protocol: TCP
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "120Mi"
        cpu: "200m"
    volumeMounts:
    - mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
      name: nginx-volume
  volumes:
  - name: nginx-volume
    configMap:
      name: nginx-config