apiVersion: v1
kind: Pod
metadata:
  name: web-server
  namespace: default
  labels:
    app: web
spec:
  containers:
  - image: my-web:v0.1
    imagePullPolicy: Never
    name: my-web
    ports:
      - containerPort: 5566
        protocol: TCP
